### ISSUE TITLE
Misused attribute name for Counters.Failed property

### ISSUE THREAD

**Issue by idulsky** [HamedFathi/TrxFileParser#2]
```
[XmlAttribute("executed")]
public int Failed { get; set; }
```

https://github.com/HamedFathi/TrxFileParser/blob/81126f050f287aa4cffbc0cae45e0eb6ed506d0b/TrxFileParser/Models/Counters.cs#L16

**Comment by HamedFathi** [comment]
@idulsky Thanks.
Fixed in the new version.
