### ISSUE TITLE
Camel casing doesn't appear to work with dotnet test generated .trx files

### ISSUE THREAD

**Issue by nzbart** [HamedFathi/TrxFileParser#3]
I am trying to deserialise a sample .trx file, but it fails because the case of the XML elements is different. Your code uses camel case, but my result file uses Pascal case (`resultSummary` vs `ResultSummary`).

I see that you changed this intentionally in 9f7d0c76225aba5fb3a1e18c38b0554551f846af for version 3.0.0.

Am I generating my .trx files differently to you somehow?

**Comment by HamedFathi** [comment]
@nzbart 

Thanks for your PR. merged as a new version v4.
```
https://www.nuget.org/packages/TrxFileParser/4.0.0
```
