### ISSUE TITLE
TrxDeserializer.Deserialize(filePath) should not modify the trx file

### ISSUE THREAD

**Issue by bitzerdk-lni** [HamedFathi/TrxFileParser#9]
Thanks for a great library that is so easy to use.

In my case I use TrxFileParser for interpreting results and uploading them to a REST service. After that my build pipeline also needs the test results, but it fails because the xmlns attribute is missing on the TestRun root element.

I was surprised to learn that the TrxDeserializer removes this attribute and rewrites the file. In my opinion a deserializing method should only deserialize - not alter the file itself.

My suggestion: Remove the attribute internally if needed, but don't rewrite the file.

**Comment by HamedFathi** [comment]
@bitzerdk-lni 

Hello,

Thanks for your kind words, you are right. it was a big mistake that I fixed please get the latest version from Nuget. (v4.3.0)

I suggest you take a look [HamedStack.VSTest](https://github.com/HamedStack/HamedStack.VSTest). It shares all details based on the `vstst.xsd` schema.
